[package]
name = "rust-worker"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38.0", features = ["full"] }
axum = { version = "0.7.5", features = ["default"] }
tracing-subscriber = "0.3.18"
tracing = "0.1.40"
serde = { version = "1.0.201", features = ["derive"] }
